-- 1. Create Users Table
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'staff',
    permissions TEXT
);

-- 2. Create Inventory Table
CREATE TABLE public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    stock NUMERIC DEFAULT 0,
    unit TEXT,
    pack_size NUMERIC DEFAULT 1,
    pack_unit TEXT,
    recipe_unit TEXT,
    recipe_unit_ratio NUMERIC DEFAULT 1,
    price NUMERIC DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Recipes Table
CREATE TABLE public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    size TEXT DEFAULT 'M',
    cogs NUMERIC DEFAULT 0,
    steps INTEGER DEFAULT 3,
    price NUMERIC DEFAULT 0,
    ingredients JSONB,
    steps_detail JSONB,
    image TEXT
);

-- 4. Create Inventory History Table
CREATE TABLE public.inventory_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT REFERENCES public.inventory(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    quantity_changed NUMERIC DEFAULT 0,
    price NUMERIC DEFAULT 0,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Insert Seed Data
INSERT INTO public.users (username, password, role, permissions) VALUES 
('Admin', 'admin123', 'admin', 'FULL'),
('Nhân viên A', '123456', 'staff', 'READ_ONLY');

INSERT INTO public.inventory (name, stock, unit, pack_size, pack_unit, recipe_unit, recipe_unit_ratio, price) VALUES 
('Hạt cà phê Robusta', 45, 'Bao', 10, 'Kg', 'gram', 10000, 1200000),
('Hạt cà phê Arabica', 8, 'Bao', 5, 'Kg', 'gram', 5000, 1250000), 
('Sữa đặc Phương Nam', 120, 'Thùng', 24, 'Lon', 'ml', 9120, 528000),
('Đường cát trắng', 5, 'Bao', 50, 'Kg', 'gram', 50000, 1000000);

INSERT INTO public.inventory_history (inventory_id, action_type, quantity_changed, price)
SELECT id, 'SEED', stock, price FROM public.inventory;

INSERT INTO public.recipes (name, size, cogs, steps, price) VALUES 
('Cà phê Đen Đá', 'M', 8000, 3, 25000),
('Bạc Xỉu', 'L', 12000, 4, 35000),
('Cà phê Muối', 'M', 15000, 5, 40000);
